Clean up code && Forget password task completed just API integration still remains.
BuildForSDGCohort2/Team-248-Frontend pull request #23
Opened 2020-08-26 17:24 UTC by AbdullahMuhammed5

2020-08-27 14:16 UTC, mohamedsgap approved these changes
So far so good, @AbdullahMuhammed5  
this suggestion for all of us to consider in the next time filling PR
* if anyone make an update or built a feature in multi files, please provide some screenshots oh what already created.

**In App.js:** you remove redux boilerplate, so we gonna switch to Context API or just to keep it simple at the moment

:+1: :+1: :100:

2020-08-27 16:53 UTC, aashrafh reviewed
Nice work, Abdullah. Just see the note I wrote about ```div```.

2020-08-27 16:53 UTC, aashrafh commented on src/components/CustomSnackbar.js
> +        <div>
You don't need a ```div``` here, the ```Snackbar``` component already wraps all the children

2020-08-27 16:53 UTC, aashrafh commented on src/components/Input.js
> +        <div>
You don't need a ```div``` here, the ```TextField``` component already wraps all the children. Don't use divs until you really need it.

2020-08-28 02:19 UTC, mwissem commented on package.json
>      "bootstrap": "^4.3.1",
`bootstrap` should be remove since you're using `material-ui` and this can affect the application loading time.

2020-08-28 05:58 UTC, mohamedsgap requested changes
@AbdullahMuhammed5 after our fellow suggestions, you can commit my changes as they asked directly, you don't need to do it manually on VS Code

2020-08-28 05:58 UTC, mohamedsgap commented on package.json
>      "bootstrap": "^4.3.1",
```suggestion
```

2020-08-28 05:58 UTC, mohamedsgap commented on src/components/CustomSnackbar.js
> +        <div>
```suggestion
```

2020-08-28 05:58 UTC, mohamedsgap commented on src/components/CustomSnackbar.js
> +        </div>
```suggestion
```

2020-08-28 05:58 UTC, mohamedsgap commented on src/components/Input.js
> +        <div>
```suggestion
```

2020-08-28 05:58 UTC, mohamedsgap commented on src/components/Input.js
> +        </div>
```suggestion
```

2020-08-29 14:14 UTC, mohamedsgap approved these changes, later dismissed
LGTM

2020-08-29 14:42 UTC, aashrafh approved these changes, later dismissed

2020-08-29 16:49 UTC, mohamedsgap approved these changes, later dismissed
Made a commit to fix some issues, after @AbdullahMuhammed5  commit the suggestions of other fellows 
:+1: :100:

2020-08-29 19:30 UTC, mwissem approved these changes, later dismissed

2020-08-29 20:23 UTC, aashrafh approved these changes, later dismissed

2020-08-30 06:53 UTC, mohamedsgap commented
@AbdullahMuhammed5 I can see that you removed `Material UI` why ? and there is still an issue, so `Netlify` didn't pass!!

2020-08-30 18:53 UTC, mohamedsgap approved these changes
Resolved all conflicts :) :+1:

2020-08-30 19:19 UTC, mwissem approved these changes

2020-08-30 19:23 UTC, RanaEmad approved these changes

2020-08-30 19:23 UTC, merged