Register task with Api integration.
BuildForSDGCohort2/Team-248-Frontend pull request #36
Opened 2020-09-06 09:26 UTC by AbdullahMuhammed5

Acceptance criteria: 

- Create registration form with the listed fields.
- Add front end validation on the required fields and validate password and email format.
- Submit the registration form to the back-end.
- Handle displaying any errors form the back-end response
- Handle redirecting to verify email message after registration.

Here is a screen for the design:
![screencapture-localhost-3000-Register-2020-09-05-16_17_51](https://user-images.githubusercontent.com/29069500/92322724-53506f00-f033-11ea-8bf4-b05c29cbe77b.png)

and here is a screen for a passed tests: 
![Screenshot from 2020-09-05 15-12-16](https://user-images.githubusercontent.com/29069500/92322780-9c082800-f033-11ea-9d3c-451fcb96f5e8.png)

2020-09-06 15:06 UTC, aashrafh approved these changes, later dismissed

2020-09-06 19:00 UTC, mohamedsgap requested changes
you are really did a great work, mate :+1:  just to mention here you need to pull the latest update from the `develop` branch especially after the `Create Offer` has merged and compare the changes to just fix the current conflict of the files. Also once you integrated with an API, you need to make sure that the form has been submitted  in the unit testing by simulating its behavior

2020-09-07 08:50 UTC, AbdullahMuhammed5 commented
> you are really did a great work, mate  just to mention here you need to pull the latest update from the `develop` branch especially after the `Create Offer` has merged and compare the changes to just fix the current conflict of the files. Also once you integrated with an API, you need to make sure that the form has been submitted in the unit testing by simulating its behavior

Thank you @mohamedsgap I did merge and resolve the conflicts.

2020-09-07 08:54 UTC, mohamedsgap approved these changes, later dismissed
So great bro :100: @AbdullahMuhammed5

2020-09-07 17:31 UTC, aashrafh submitted a review, later dismissed

2020-09-09 10:23 UTC, mohamedsgap approved these changes

2020-09-09 10:29 UTC, mohamedsgap approved these changes

2020-09-09 17:04 UTC, aashrafh approved these changes
Good work

2020-09-09 19:28 UTC, mwissem approved these changes

2020-09-09 19:28 UTC, ghost commented on package.json
> +    "bootstrap": "^4.3.1",
bootstrap is not needed, it should be removed.

2020-09-09 19:30 UTC, merged

2020-09-09 19:48 UTC, mohamedsgap commented on package.json
> +    "bootstrap": "^4.3.1",
I think some of MUI library is using it, @AbdullahMuhammed5 isn't it ?